move_tasks:
  - trigger: /storage2/Temp/Ready/Movies/move.now
    source: /storage2/Temp/Ready/Movies/
    target: /storage1/Movies/
    user: plex
    group: plexreaders
    file_mode: "0640"
    dir_mode: "0750"
    overwrite: true
    pre:
      - command: "/usr/local/bin/pre-movie-hook.sh"
        uid: 1001
        gid: 1001
        timeout: 600
    post:
      - command: "/usr/local/bin/post-movie-hook.sh"
        uid: 1001
        gid: 1001
      - command: "logger 'Finished moving movies'"

  - trigger: /storage2/Temp/Ready/TV/move.now
    source: /storage2/Temp/Ready/TV/
    target: /storage1/TV/
    user: plex
    group: plexreaders
    file_mode: "0640"
    dir_mode: "0750"
    overwrite: false

generic_tasks:
  - trigger: /home/chris/some-file.txt
    run:
      - command: "/usr/local/bin/some-script.sh"
        uid: 1000
        gid: 1000
        timeout: 600
      - command: "/usr/local/bin/some-other-script.sh"

  - trigger: /var/www/html/stats.csv
    run:
      - command: "/usr/local/bin/generate-report.sh"